name: Log‑Demo (Windows)

# Manual trigger – you can change to `push` or `schedule` if you prefer
on:
  workflow_dispatch:

jobs:
  demo-log-handling:
    runs-on: windows-latest
    steps:
      # ---------------------------------------------------------
      # 1️⃣ Checkout (optional – keeps the workspace tidy)
      # ---------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------------------------------------------------------
      # 2️⃣ Prepare a *real* temporary log file (empty file guarantees existence)
      # ---------------------------------------------------------
      - name: Prepare temporary log file
        id: prep_log                                   # <-- step ID (underscore)
        run: |
          # Build a unique filename in the runner's Temp folder
          $logPath = Join-Path $env:TEMP ("log_demo_" + [guid]::NewGuid().ToString() + ".txt")
          # Force creation of an empty file so the path definitely exists
          New-Item -Path $logPath -ItemType File -Force | Out-Null

          # Export the path for later steps:
          #   - As an *output* (used with ${{ steps.prep_log.outputs.log_path }})
          #   - As an *environment variable* (available as $DEMO_LOG)
          echo "log_path=$logPath" >> $env:GITHUB_OUTPUT
          echo "DEMO_LOG=$logPath" >> $env:GITHUB_ENV

      # ---------------------------------------------------------
      # 3️⃣ Run demo commands (everything captured to the log file)
      # ---------------------------------------------------------
      - name: Run demo commands (output captured to log)
        env:
          DEMO_LOG: ${{ steps.prep_log.outputs.log_path }}   # <-- exact path
        run: |
          # The `{ … }` block groups the commands.
          # `*> $DEMO_LOG` writes **all** streams (stdout, stderr, warnings, verbose, etc.) to the file.
          {
            # Use Write-Output (or plain strings) – Write-Host is NOT captured by redirection.
            Write-Output "=== Demo run started at $(Get-Date) ==="
            Write-Output ""

            Write-Output "🔹 Greeting from PowerShell:"
            Write-Output "Hello from PowerShell!"
            Write-Output ""

            Write-Output "🔹 OS information (first 5 lines of `systeminfo`):"
            systeminfo | Select-Object -First 5 | Out-String
            Write-Output ""

            Write-Output "🔹 List of files in the temporary folder:"
            Get-ChildItem -Path $env:TEMP | Format-Table Name, Length, LastWriteTime | Out-String
            Write-Output ""

            Write-Output "🔹 Running a tiny R script (prints from R):"
            # R may not be installed on the runner yet; the error (if any) will still be captured.
            Rscript -e 'cat("Hello from R!\n")'
            Write-Output ""

            Write-Output "=== Demo run finished ==="
          } *> $DEMO_LOG

      # ---------------------------------------------------------
      # 4️⃣ Show the log file (will always exist now)
      # ---------------------------------------------------------
      - name: Display demo log
        # NOTE: we **must** use the same output reference here
        run: |
          Write-Host "`n===== Demo log (START) ====="
          Get-Content -Path ${{ steps.prep_log.outputs.log_path }}
          Write-Host "===== Demo log (END) =====`n"
