name: Test minioclient install (Windows only)

# ------------------------------------------------------------------
# Run manually – you press the “Run workflow” button whenever you want.
# ------------------------------------------------------------------
on:
  workflow_dispatch:          # manual trigger

jobs:
  windows-minioclient:
    runs-on: windows-latest               # ← only Windows
    env:
      # Prevent remotes from treating warnings as errors
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      # ---------------------------------------------------------
      # 1️⃣ Checkout the repo (not strictly needed for the install,
      #    but keeps the workspace tidy and lets you reference files)
      # ---------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------------------------------------------------------
      # 2️⃣ Install R (includes Rtools automatically)
      # ---------------------------------------------------------
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4'          # keep the same version you use locally
          use-public-rspm: true
          install-rtools: true       # ensures the MinGW toolchain is on PATH

      # ---------------------------------------------------------
      # 3️⃣ Install Windows system libraries needed by minioclient
      # ---------------------------------------------------------
      - name: Install OpenSSL, pkg‑config and CMake
        run: |
          choco install openssl.light -y
          choco install pkgconfiglite -y
          choco install cmake -y

      # ---------------------------------------------------------
      # 4️⃣ Cache the user library (speeds up repeated runs)
      # ---------------------------------------------------------
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: windows-r-${{ hashFiles('**/*.R') }}
          restore-keys: windows-r-

      # ---------------------------------------------------------
      # 5️⃣ Install the `remotes` helper package (used to pull from GitHub)
      # ---------------------------------------------------------
      - name: Install remotes package
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}   # authentication token
        run: |
          Rscript -e 'install.packages("remotes")'

      # ---------------------------------------------------------
      # 6️⃣ Install minioclient – **verbose** (shows all compile output)
      # ---------------------------------------------------------
      - name: Install minioclient (verbose)
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Rscript -e '
            # Show some context
            cat("R version:", getRversion(), "\n")
            cat(".libPaths():", .libPaths(), "\n")

            # Make sure the token is visible to remotes
            Sys.setenv(GITHUB_PAT = Sys.getenv("GITHUB_PAT"))

            # Try the install and print any error that occurs
            tryCatch(
              {
                remotes::install_github(
                  "cboettig/minioclient",
                  ref = "main",
                  upgrade = "never",
                  dependencies = FALSE,   # only the minioclient source itself
                  quiet = FALSE          # <‑‑ crucial – show compile output
                )
                cat("\n✅ minioclient installed successfully!\n")
              },
              error = function(e) {
                cat("\n❌ Installation failed – here is the error object:\n")
                print(e)                 # prints the full R error message
                quit(status = 1)         # exit with non‑zero code after printing
              }
            )
          '

      # ---------------------------------------------------------
      # 7️⃣ (Optional) Load the package to prove it works
      # ---------------------------------------------------------
      - name: Load minioclient to confirm installation
        if: success()
        run: |
          Rscript -e 'library(minioclient); cat("Package loaded – ready to go!\n")'
