name: Minioclient install test (Windows)

# Run only when you click “Run workflow”
on:
  workflow_dispatch:

jobs:
  install-minioclient:
    runs-on: windows-latest
    env:
      # Prevent warnings from turning into hard errors
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      # ---------------------------------------------------------
      # 1️⃣ Checkout (optional – keeps the workspace tidy)
      # ---------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------------------------------------------------------
      # 2️⃣ Install R (includes the default Rtools toolchain)
      # ---------------------------------------------------------
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4'                     # same version you use locally
          use-public-rspm: true
          windows-path-include-rtools: true     # puts Rtools on the PATH

      # ---------------------------------------------------------
      # 3️⃣ Install the native libraries that minioclient depends on
      # ---------------------------------------------------------
      - name: Install OpenSSL, pkg‑config and CMake
        run: |
          choco install openssl.light -y
          choco install pkgconfiglite -y
          choco install cmake -y

      # ---------------------------------------------------------
      # 4️⃣ Install minioclient from GitHub and report the outcome
      # ---------------------------------------------------------
      - name: Install minioclient (show full error)
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Rscript -e '
            # Make the token visible to remotes (required for GitHub API calls)
            Sys.setenv(GITHUB_PAT = Sys.getenv("GITHUB_PAT"))

            cat("\n=== STARTING minioclient INSTALL ===\n")

            tryCatch(
              {
                remotes::install_github(
                  "cboettig/minioclient",
                  ref = "main",
                  upgrade = "never",
                  dependencies = FALSE,
                  quiet = FALSE          # show compilation output
                )
                cat("\n✅ minioclient installed successfully!\n")
              },
              error = function(e) {
                cat("\n❌ Installation FAILED – here is the full error object:\n")
                print(e)               # <-- this is the piece you need
                # Flush the console before quitting so the output is not lost
                flush.console()
                quit(status = 1)       # keep the step failing
              }
            )
          '

      # ---------------------------------------------------------
      # 5️⃣ (Optional) Verify the package can be loaded
      # ---------------------------------------------------------
      - name: Load minioclient (sanity check)
        if: success()
        run: |
          Rscript -e 'library(minioclient); cat("✅ Package loaded successfully.\n")'
