name: Minioclient install test (Windows)

# Run only when you click “Run workflow”
on:
  workflow_dispatch:

jobs:
  install-minioclient:
    runs-on: windows-latest
    env:
      # Prevent warnings from turning into hard errors
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      # ---------------------------------------------------------
      # 1️⃣ Checkout (optional – keeps the workspace tidy)
      # ---------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------------------------------------------------------
      # 2️⃣ Install R (includes the default Rtools toolchain)
      # ---------------------------------------------------------
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4'                     # same version you use locally
          use-public-rspm: true
          windows-path-include-rtools: true     # puts Rtools on the PATH

      # ---------------------------------------------------------
      # 3️⃣ Install the native libraries that minioclient depends on
      # ---------------------------------------------------------
      - name: Install OpenSSL, pkg‑config and CMake
        run: |
          choco install openssl.light -y
          choco install pkgconfiglite -y
          choco install cmake -y

      # ---------------------------------------------------------
      # 4️⃣ Install minioclient from GitHub and report the outcome
      # ---------------------------------------------------------
      - name: Install minioclient (force‑log to file)
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create a real temporary file that definitely exists
          $logPath = Join-Path $env:TEMP ("minioclient_log_" + [guid]::NewGuid().ToString() + ".txt")
          $env:MINIO_LOG = $logPath

          Rscript -e '
            Sys.setenv(GITHUB_PAT = Sys.getenv("GITHUB_PAT"))
            logFile <- Sys.getenv("MINIO_LOG")
            con <- file(logFile, open = "wt")
            sink(con, type = "output")
            sink(con, type = "message")
            on.exit({
              sink(type = "message")
              sink()
              close(con)
            }, add = TRUE)

            cat("=== STARTING minioclient INSTALL ===\n")
            flush.console()

            tryCatch(
              {
                remotes::install_github(
                  "cboettig/minioclient",
                  ref = "main",
                  upgrade = "never",
                  dependencies = FALSE,
                  quiet = FALSE
                )
                cat("\n✅ minioclient installed successfully!\n")
              },
              error = function(e) {
                cat("\n❌ Installation FAILED – error object:\n")
                print(e)
                quit(status = 1)
              }
            )
          '

          # Show the whole log in the Actions UI
          Write-Host "`n===== minioclient install log (START) ====="
          Get-Content -Path $logPath
          Write-Host "===== minioclient install log (END) =====`n"
      # ---------------------------------------------------------
      # 5️⃣ (Optional) Verify the package can be loaded
      # ---------------------------------------------------------
      - name: Load minioclient (sanity check)
        if: success()
        run: |
          Rscript -e 'library(minioclient); cat("✅ Package loaded successfully.\n")'
