name: Test minioclient install (Windows only)

on:
  workflow_dispatch:          # manual trigger

jobs:
  windows-minioclient:
    runs-on: windows-latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true   # keep warnings from aborting

    steps:
      # ---------------------------------------------------------
      # 1️⃣ Checkout (optional, just keeps the workspace tidy)
      # ---------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------------------------------------------------------
      # 2️⃣ Install R (this also pulls in the default Rtools version)
      # ---------------------------------------------------------
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4'          # same version you use locally
          use-public-rspm: true
          # The flag below tells the action to *add* the Rtools directories
          # to the PATH after installing them.
          windows-path-include-rtools: true

      # ---------------------------------------------------------
      # 3️⃣ (Alternative) Explicitly install Rtools via Chocolatey
      # ---------------------------------------------------------
      # If you prefer an explicit step, uncomment the block below.
      # It does the same thing as the flag above, but you’ll see the
      # installation logs in the Actions UI.
      #
      # - name: Install Rtools via Chocolatey
      #   run: |
      #     choco install rtools -y
      #     # Verify that gcc is reachable
      #     gcc --version

      # ---------------------------------------------------------
      # 4️⃣ Install additional Windows system libs needed by minioclient
      # ---------------------------------------------------------
      - name: Install OpenSSL, pkg‑config and CMake
        run: |
          choco install openssl.light -y
          choco install pkgconfiglite -y
          choco install cmake -y

      # ---------------------------------------------------------
      # 5️⃣ Cache the user library (speeds up repeated runs)
      # ---------------------------------------------------------
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: windows-r-${{ hashFiles('**/*.R') }}
          restore-keys: windows-r-

      # ---------------------------------------------------------
      # 6️⃣ Install the `remotes` helper package (needed for GitHub installs)
      # ---------------------------------------------------------
      - name: Install remotes package
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Rscript -e 'install.packages("remotes")'

      # ---------------------------------------------------------
      # 7️⃣ Install minioclient – **verbose** (shows all compile output)
      # ---------------------------------------------------------
      - name: Install minioclient (verbose)
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Rscript -e '
            cat("R version:", getRversion(), "\n")
            cat(".libPaths():", .libPaths(), "\n")
            Sys.setenv(GITHUB_PAT = Sys.getenv("GITHUB_PAT"))
            tryCatch(
              {
                remotes::install_github(
                  "cboettig/minioclient",
                  ref = "main",
                  upgrade = "never",
                  dependencies = FALSE,
                  quiet = FALSE          # <‑‑ show compilation messages
                )
                cat("\n✅ minioclient installed successfully!\n")
              },
              error = function(e) {
                cat("\n❌ Installation failed – here is the error object:\n")
                print(e)
                quit(status = 1)
              }
            )
          '

      # ---------------------------------------------------------
      # 8️⃣ (Optional) Load the package to confirm it works
      # ---------------------------------------------------------
      - name: Load minioclient to confirm installation
        if: success()
        run: |
          Rscript -e 'library(minioclient); cat("Package loaded – ready to go!\n")'
