name: Minioclient install test (Windows)

# Manual trigger only
on:
  workflow_dispatch:

jobs:
  install-minioclient:
    runs-on: windows-latest
    env:
      # Prevent warnings from turning into hard errors
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      # ---------------------------------------------------------
      # 1️⃣ Checkout (optional – keeps the workspace tidy)
      # ---------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------------------------------------------------------
      # 2️⃣ Install R (includes the default Rtools toolchain)
      # ---------------------------------------------------------
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4'                     # same version you use locally
          use-public-rspm: true
          windows-path-include-rtools: true     # puts Rtools on the PATH

      # ---------------------------------------------------------
      # 3️⃣ Install the native libraries that minioclient depends on
      # ---------------------------------------------------------
      - name: Install OpenSSL, pkg‑config and CMake
        run: |
          choco install openssl.light -y
          choco install pkgconfiglite -y
          choco install cmake -y

      # ---------------------------------------------------------
      # 4️⃣ Create a *real* temporary log file (empty file guarantees existence)
      # ---------------------------------------------------------
      - name: Prepare temporary log file
        id: prep-log
        run: |
          $logPath = Join-Path $env:TEMP ("minioclient_log_" + [guid]::NewGuid().ToString() + ".txt")
          # Force creation of an empty file so the path definitely exists
          New-Item -Path $logPath -ItemType File -Force | Out-Null
          # Export the path for later steps (both as an output and as an env var)
          echo "log_path=$logPath" >> $GITHUB_OUTPUT
          echo "MINIO_LOG=$logPath" >> $GITHUB_ENV

      # ---------------------------------------------------------
      # 5️⃣ Install minioclient – capture **all** console output via shell redirection
      # ---------------------------------------------------------
      - name: Install minioclient (full log captured by the shell)
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}   # token for GitHub API
          MINIO_LOG: ${{ steps.prep-log.outputs.log_path }}
        run: |
          # The whole R command is wrapped in single quotes for PowerShell.
          # We redirect BOTH stdout and stderr to the log file we created.
          Rscript -e '
            # -------------------------------------------------------
            # Make the token visible to remotes (required for GitHub API)
            # -------------------------------------------------------
            Sys.setenv(GITHUB_PAT = Sys.getenv("GITHUB_PAT"))

            cat("\n=== STARTING minioclient INSTALL ===\n")
            flush.console()

            # -------------------------------------------------------
            # Perform the install – any error will be printed automatically
            # -------------------------------------------------------
            remotes::install_github(
              "cboettig/minioclient",
              ref = "main",
              upgrade = "never",
              dependencies = FALSE,
              quiet = FALSE          # show compilation output
            )

            cat("\n✅ minioclient installed successfully!\n")
          ' > ${{ steps.prep-log.outputs.log_path }} 2>&1

      # ---------------------------------------------------------
      # 6️⃣ Show the log file (will always exist now)
      # ---------------------------------------------------------
      - name: Show minioclient install log
        run: |
          Write-Host "`n===== minioclient install log (START) ====="
          Get-Content -Path ${{ steps.prep-log.outputs.log_path }}
          Write-Host "===== minioclient install log (END) =====`n"

      # ---------------------------------------------------------
      # 7️⃣ (Optional) Verify the package can be loaded
      # ---------------------------------------------------------
      - name: Load minioclient (sanity check)
        if: success()
        run: |
          Rscript -e 'library(minioclient); cat("✅ Package loaded successfully.\n")'
