name: R CMD check (on‑demand)

on:
  workflow_dispatch:          # manual trigger only

jobs:
  # -------------------------------------------------
  # Linux job
  # -------------------------------------------------
  linux-check:
    runs-on: ubuntu-latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up R (Linux)
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4'          # adjust if needed
          use-public-rspm: true

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/*.R') }}
          restore-keys: ${{ runner.os }}-r-

      - name: Install R dependencies (incl. minioclient)
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Rscript -e '
            install.packages("remotes")
            for(i in 1:3){
              tryCatch(
                remotes::install_deps(dependencies = TRUE, upgrade = "always"),
                error = function(e){ if(i == 3) stop(e) else Sys.sleep(10) }
              )
            }
            Sys.setenv(GITHUB_PAT = Sys.getenv("GITHUB_PAT"))
            for(i in 1:3){
              tryCatch(
                remotes::install_github("cboettig/minioclient", ref = "main", upgrade = "never"),
                error = function(e){ if(i == 3) stop(e) else Sys.sleep(10) }
              )
            }
          '

      - name: R CMD check
        run: |
          R CMD check . --as-cran --no-manual --no-build-vignettes


  # -------------------------------------------------
  # Windows job
  # -------------------------------------------------
  windows-check:
    runs-on: windows-latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up R (Windows + Rtools)
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4'
          use-public-rspm: true

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/*.R') }}
          restore-keys: ${{ runner.os }}-r-

      # (Optional) install extra system libs if you ever hit missing‑header errors
      # - name: Install system libs
      #   run: choco install openssl.light -y

      - name: Install R dependencies (incl. minioclient)
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Rscript -e '
            install.packages("remotes")
            for(i in 1:3){
              tryCatch(
                remotes::install_deps(dependencies = TRUE, upgrade = "always"),
                error = function(e){ if(i == 3) stop(e) else Sys.sleep(10) }
              )
            }
            Sys.setenv(GITHUB_PAT = Sys.getenv("GITHUB_PAT"))
            for(i in 1:3){
              tryCatch(
                remotes::install_github("cboettig/minioclient", ref = "main", upgrade = "never"),
                error = function(e){ if(i == 3) stop(e) else Sys.sleep(10) }
              )
            }
          '

      - name: R CMD check
        run: |
          R CMD check . --as-cran --no-manual --no-build-vignettes
